### ISSUE TITLE
Object.observe() is NOT part of ES6 specification

### ISSUE THREAD

**Issue by StyMaar** [azazdeaz/LazyJsonUndoRedo#2]
Hi,
In the project description and in the README.md file you refer to Object.observe as part of the ECMAScript 6 specification ("ES6 Object.observe()"), which is not the case at all. 
Object.observe is not a standard feature, it a V8 specific feature and it's unlikely to become one before several years (it's currently a part of ES 7 proposals).
There is a lot of hype around ES6 nowadays, with tons of new/revolutionary features (iterators, arrow functions, symbols, destructuring …) and it's actually pretty confusing. Please don't add more confusion mixing up ES 6 features that will be standardized this year, with browser-specific features that are highly experimental.

Thank you.

**Comment by azazdeaz** [comment]
You're right. Thanks for pointing that out!

**Comment by StyMaar** [comment]
Thanks for your reactivity ! There is still an allusion to ES6 in the project description (on top of the github page)

**Comment by azazdeaz** [comment]
Oh, my bad, thanks again!
